### ISSUE TITLE
suggestion: use smugs.safe.moe

### ISSUE THREAD

**Issue by jithatsonei** [Fshy/FshyBot#5]
/home/alucard/smugs.trade/i# ls -l | wc -l
1245

yes i have a REST api service for serving pictures of smug anime girls with patronizing looks on their faces stop judging me

**Comment by Fshy** [comment]
Didn't receive a verification email my dude :thinking: 
Also whats your endpoint?

**Comment by jithatsonei** [comment]
my bad, endpoint for requesting images is https://smugs.safe.moe/api/v1/i/r no auth needed. 

example (ghetto) implementation at https://github.com/Pitu/Kuro/blob/master/commands/smug.js
